### ISSUE TITLE
collapse book parts

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/bacterial-genomics#3]
not urgent, but if we want to collapse the book parts, we can add this to `_quarto.yml` under the `book` specification:

```yml
book:
  sidebar: 
    collapse-level: 1
```
